"""Regenerate the self-contained external kit (C:\\Users\\marcu\\Desktop\\str-mapper-experiment) from data/reader/kit-v1."""
import json, shutil, sys
from pathlib import Path
ROOT = Path(__file__).resolve().parent.parent; sys.path.insert(0, str(ROOT))
from corpus_engine.domain import load_domain                                     # noqa: E402
if __name__ == "__main__":
    dst = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"C:\Users\marcu\Desktop\str-mapper-experiment")
    dom = load_domain(); kit = json.loads((ROOT / dom.reader.kit_path).read_text(encoding="utf-8"))
    (dst / "batches").mkdir(parents=True, exist_ok=True); (dst / "reference").mkdir(exist_ok=True); (dst / "prompts").mkdir(exist_ok=True)
    for b in kit["batches"]:
        for c in b["cases"]:
            c["opinion_text"] = kit["texts"][str(c["case_id"])]["raw_text"]
        (dst / "batches" / f"{b['batch_id']}.json").write_bytes(json.dumps(b, indent=1).encode("utf-8"))
    (dst / "reference" / "human.json").write_bytes(json.dumps(kit["reference"], indent=1).encode("utf-8"))
    shutil.copy(ROOT / "domains" / dom.name / dom.reader.codebooks_dir / f"{dom.reader.codebook}.md", dst / "prompts" / "mapper.md")
    (dst / "KIT-VERSION").write_bytes(b"kit-v1 (human-adjudicated reference; regenerated by tools/export_reader_kit.py)\n")
    print("exported", len(kit["batches"]), "batches to", dst)
